#!/usr/bin/env python
import os
import json

token = open("token").read().strip()
cmd = "wget -O - https://api.telegram.org/bot"+ token +"/getUpdates"

res = os.popen(cmd).read()
print res
res = json.loads(res)
#info = json.load(open("getUpdates"))

result_list = res["result"]
for res in result_list:
    msg = res["message"]
    s  = str(msg["date"]) +" "
    s += str(msg["from"]["first_name"])
    if "text" in msg.keys():
        s += " "+ msg["text"]
    print s
